import type { NextPage } from "next";
import Head from "next/head";
import { InboxIcon } from "@heroicons/react/24/solid";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-row overflow-auto text-[#3c4149]">
        <div className="w-[220px] flex-shrink-0 border-r border-[#E7E9EB]">
          <div className="flex h-[62px] items-center border-b border-[#E7E9EB]">
            <span className="ml-4">Logle</span>
          </div>
          <div className="px-3 pt-3 text-[13px]">
            <div>
              <div className="my-[1px] flex h-[27px] cursor-pointer flex-row items-center rounded pl-2 transition-colors hover:bg-[#f1f3f9]">
                <div className="mr-2 h-4 w-4">
                  <InboxIcon />
                </div>
                <span>feed</span>
              </div>
            </div>
            <div className="mt-2">
              <div className="flex h-6 cursor-pointer items-center rounded-md px-2 transition-colors hover:bg-[#f1f3f9]">
                <span className="text-xs font-medium text-[#6b6f76]">
                  Your Projects
                </span>
              </div>
              <div className="flex flex-col">
                {["Snapify", "Logle", "Tablane"].map((x) => (
                  <div
                    key={x}
                    className="flex h-6 cursor-pointer items-center rounded-md px-2 transition-colors hover:bg-[#f1f3f9]"
                  >
                    <span className="text-xs font-medium text-[#6b6f76]">
                      {x}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
        <div className="flex w-full flex-col">
          <div className="flex h-[62px] items-center border-b border-[#E7E9EB]">
            <span className="ml-4 font-bold">Feed</span>
          </div>
          <div className="flex flex-col items-center justify-center">
            {[1, 2, 3].map((x) => (
              <div
                key={x}
                className="mt-6 flex w-[480px] flex-row rounded-lg border border-[#00000014] p-6 text-[#474747]"
              >
                <div className="mr-4 flex h-12 w-12 shrink-0 items-center justify-center rounded-lg border border-[#00000014] bg-[#dad1bf1a]">
                  FX
                </div>
                <div className="flex grow flex-col">
                  <div>
                    <span className="font-bold">Form Submitted</span>
                  </div>
                  <div className="flex flex-row justify-between">
                    <span>A form was submitted</span>
                    <span>1:37 PM</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
