import type { NextPage } from "next";
import Head from "next/head";

import FeedList from "~/components/FeedList";
import Sidebar from "~/components/Sidebar";

const events = [
  {
    event: "Form Submitted",
    description: "A form was submitted",
    timestamp: 1683419171057,
    icon: "🔥",
  },
  {
    event: "Form Submitted",
    description: "A form was submitted",
    timestamp: 1683419171051,
    icon: "🔥",
  },
  {
    event: "Form Submitted",
    description: "A form was submitted",
    timestamp: 1683419171053,
    icon: "🔥",
  },
];

const Feed: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-row overflow-auto text-[#3c4149]">
        <Sidebar />
        <div className="flex w-full flex-col">
          <div className="flex h-[62px] items-center border-b border-[#E7E9EB]">
            <span className="ml-4 font-bold">Feed</span>
          </div>
          <FeedList events={events} />
        </div>
      </main>
    </>
  );
};

export default Feed;
